package com.tothenew.bluebox.bluebox.enums;

public enum FromStatus {
  ORDER_PLACED,
  CANCELLED,
  ORDER_REJECTED,
  ORDER_CONFIRMED,
  ORDER_SHIPPED,
  DELIVERED,
  RETURN_REQUESTED,
  RETURN_REJECTED,
  RETURN_APPROVED,
  PICK_UP_INITIATED,
  PICK_UP_COMPLETED,
  REFUND_INITIATED,
  REFUND_COMPLETED,
}
